#pragma once
#include <memory>
#include <vector>
#include "SceneBase.h"
class Stage;
class SkyDome;
class Player;
class EnemyManager;
class CellBase;

class GameScene : public SceneBase
{

public:
	
	// コンストラクタ
	GameScene(void);

	// デストラクタ
	~GameScene(void) override;

	// 初期化
	void Init(void) override;

	// 更新
	void Update(void) override;

	// 描画
	void Draw(void) override;

	// 解放
	void Release(void) override;

private:

	Stage* stage_;
	SkyDome* skyDome_;
	Player* player_;
	EnemyManager* enemyManager_;
	std::vector<std::shared_ptr<CellBase>> playerCells_;	// tmp
	std::vector<std::shared_ptr<CellBase>> enemyCells_;	// tmp
	std::vector<std::shared_ptr<CellBase>> selectCells_;	// tmp

	static constexpr int PLAYER_FIELD_CELL_Y = 5;	// フィールドのセル高さ
	static constexpr int PLAYER_FIELD_CELL_X = 5;	// フィールドのセル幅
	static constexpr int PLAYER_FIELD_CELL_SIZE = 50;	// フィールドのセルサイズ
	static constexpr int ENEMY_FIELD_CELL_Y = 4;	// フィールドのセル高さ
	static constexpr int ENEMY_FIELD_CELL_X = 4;	// フィールドのセル幅
	static constexpr int ENEMY_FIELD_CELL_SIZE = 50;	// フィールドのセルサイズ
	static constexpr int SELECT_FIELD_CELL_Y = 7;	// フィールドのセル高さ
	static constexpr int SELECT_FIELD_CELL_X = 48;	// フィールドのセル幅
	static constexpr int SELECT_FIELD_CELL_SIZE = 40;	// フィールドのセルサイズ

	enum class CELL_TYPE
	{
		NONE = 0,
		ATTACK,
		DEFENSE,
		BUFF,
		DEBUFF,
	};
	CELL_TYPE playerField_[PLAYER_FIELD_CELL_Y][PLAYER_FIELD_CELL_X] = {
		{ CELL_TYPE::ATTACK, CELL_TYPE::DEFENSE, },
		{ CELL_TYPE::BUFF, CELL_TYPE::DEBUFF, },
	};
	CELL_TYPE enemyField_[ENEMY_FIELD_CELL_Y][ENEMY_FIELD_CELL_X] = {
		{ CELL_TYPE::ATTACK, CELL_TYPE::DEFENSE, },
		{ CELL_TYPE::BUFF, CELL_TYPE::DEBUFF, },
	};
	CELL_TYPE selectField_[SELECT_FIELD_CELL_Y][SELECT_FIELD_CELL_X] = {
		{ CELL_TYPE::NONE, CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::ATTACK, },
		{ CELL_TYPE::NONE, CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::ATTACK, },
		{ CELL_TYPE::NONE, CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::ATTACK, },
		{ CELL_TYPE::NONE, CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::ATTACK, },
		{ CELL_TYPE::NONE, CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::ATTACK, },
		{ CELL_TYPE::NONE, CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::ATTACK, },
		{ CELL_TYPE::NONE, CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::NONE,CELL_TYPE::ATTACK, },
	};

};
